#!/usr/bin/env python3
import argparse
import json
import urllib.request


GITHUB_API = "https://api.github.com"
MARKER = "<!-- weave-ci-evidence-manifest -->"


def build_comment_body(manifest_path: str, head_sha: str, summary_markdown: str) -> str:
    return (
        f"{MARKER}\n"
        f"## CI Evidence Manifest\n\n"
        f"- SHA: `{head_sha}`\n"
        f"- Manifest: `{manifest_path}`\n\n"
        f"{summary_markdown.strip()}\n"
    )


def api_request(
    method: str, path: str, token: str, payload: dict | None = None
) -> dict | list:
    data = None
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")

    req = urllib.request.Request(
        f"{GITHUB_API}{path}",
        method=method,
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req) as response:
        raw = response.read().decode("utf-8")
        return json.loads(raw) if raw else {}


def upsert_comment(repo: str, pr_number: int, token: str, body: str) -> str:
    comments = api_request(
        "GET", f"/repos/{repo}/issues/{pr_number}/comments?per_page=100", token
    )
    if not isinstance(comments, list):
        raise ValueError("unexpected comments response")

    for comment in comments:
        if not isinstance(comment, dict):
            continue
        current_body = comment.get("body") or ""
        if MARKER in current_body:
            comment_id = comment["id"]
            updated = api_request(
                "PATCH",
                f"/repos/{repo}/issues/comments/{comment_id}",
                token,
                payload={"body": body},
            )
            return updated.get("html_url", "")

    created = api_request(
        "POST",
        f"/repos/{repo}/issues/{pr_number}/comments",
        token,
        payload={"body": body},
    )
    return created.get("html_url", "")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Upsert deterministic evidence manifest comment on PR"
    )
    parser.add_argument("--repo", required=True, help="owner/repo")
    parser.add_argument("--pr-number", required=True, type=int)
    parser.add_argument("--token", required=True)
    parser.add_argument("--manifest-path", required=True)
    parser.add_argument("--head-sha", required=True)
    parser.add_argument(
        "--summary-file",
        required=True,
        help="markdown file generated by evidence_manifest.py",
    )
    args = parser.parse_args()

    summary = open(args.summary_file, encoding="utf-8").read()
    body = build_comment_body(args.manifest_path, args.head_sha, summary)
    url = upsert_comment(args.repo, args.pr_number, args.token, body)
    print(f"Upserted PR evidence comment: {url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
